inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
  TargetRubyVersion: 3.2
  NewCops: enable

Style/Documentation:
  Exclude:
    - 'app/mailers/**/*'
    - 'app/models/**/*'
    - 'config/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
